//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mouse_Bounder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BOUND_WHEN_FOCUSED {
            get {
                return ((bool)(this["BOUND_WHEN_FOCUSED"]));
            }
            set {
                this["BOUND_WHEN_FOCUSED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REMEMBER_LAST_PROCESS {
            get {
                return ((bool)(this["REMEMBER_LAST_PROCESS"]));
            }
            set {
                this["REMEMBER_LAST_PROCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BORDER_OFFSET {
            get {
                return ((int)(this["BORDER_OFFSET"]));
            }
            set {
                this["BORDER_OFFSET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BOUND_TOGGLE_KEY_ENABLED {
            get {
                return ((bool)(this["BOUND_TOGGLE_KEY_ENABLED"]));
            }
            set {
                this["BOUND_TOGGLE_KEY_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BOUND_TOGGLE_KEY {
            get {
                return ((int)(this["BOUND_TOGGLE_KEY"]));
            }
            set {
                this["BOUND_TOGGLE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_PROCESS {
            get {
                return ((string)(this["LAST_PROCESS"]));
            }
            set {
                this["LAST_PROCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ALWAYS_ON_TOP {
            get {
                return ((bool)(this["ALWAYS_ON_TOP"]));
            }
            set {
                this["ALWAYS_ON_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_BIND_TO_REMEMBERED_PROCESSES {
            get {
                return ((bool)(this["AUTO_BIND_TO_REMEMBERED_PROCESSES"]));
            }
            set {
                this["AUTO_BIND_TO_REMEMBERED_PROCESSES"] = value;
            }
        }
    }
}
